import pint


UREG = pint.UnitRegistry()

TIME_UNIT = UREG.minute
DEPTH_UNIT = UREG.foot
VOLUME_UNIT = UREG.foot ** 3
PRESSURE_UNIT = UREG.psi
VOLUME_RATE_UNIT = VOLUME_UNIT / TIME_UNIT
PRESSURE_RATE_UNIT = PRESSURE_UNIT / TIME_UNIT

TIME_INCREMENT = (1.0 * UREG.second).to(TIME_UNIT)
