#!/bin/zsh

# start a jupyter notebook in an already running docker container.
# run this from the host.
# you must already have built and run the docker container and built the library.

set -e 
set -o pipefail

# get the src directory from the container instead of hardcoding here
SRC_DIR=$(docker exec cenote printenv SRC_DIR)
docker exec cenote jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --notebook-dir $SRC_DIR/jupyter
