#!/bin/zsh

# Meant to be run from within docker container.
# Fix style errors in place.

set -e 
set -o pipefail

# c++ stuff
STYLE_FILE=$SRC_DIR/setup/.clang-format
find $SRC_DIR/cpp -regex '.*\.\(cpp\|h\|inl\)' -exec clang-format -i {} -style=file:$STYLE_FILE \;

# python setuff
black \
    $SRC_DIR/py/cenote \
    $SRC_DIR/py/test \
    --line-length 100 \
    -t py310
